# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        required: true
        type: string
        default: "v0.1"
 
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Build
      id: myval
      run: |
        if [ "${{ github.event.inputs.tag }}" ]; then
          tmp_tag="${{ github.event.inputs.tag }}"
        else
          tmp_tag="${{ github.ref_name }}"
        fi
        go build -v ./... &&
        echo "release_status=ok" >> $GITHUB_OUTPUT &&
        echo "release_tag=${tmp_tag}" >> $GITHUB_OUTPUT

    - name: Release
      uses: softprops/action-gh-release@v2
      if: "steps.myval.outputs.release_status == 'ok' && !cancelled()"
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        name: "${{ steps.myval.outputs.release_tag }}"
        body: "远程执行命令, 多主机并发"
        files: rrcmd

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.MY_TOKEN }}
        retain_days: 1
        keep_minimum_runs: 3

    - name: Delete older Releases
      uses: dev-drprasad/delete-older-releases@v0.3.4
      if: "!cancelled()"
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        keep_latest: 3
        delete_tags: true