# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Manual Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "The tag version you want to create"
        required: true
        type: string
        default: "v0.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.MY_TOKEN }}
          RELEASE_TAG: ${{ github.event.inputs.tag_name }}
          RELEASE_TITLE: ${{ github.event.inputs.tag_name }}
          RELEASE_NOTES: "远程执行命令, 多主机并发"
        run: |
          echo "--- 正在处理 Release $RELEASE_TAG ---"    
          # 检查 Release 是否已经存在
          if gh release view "$RELEASE_TAG" >/dev/null 2>&1; then
            echo "Release 已存在，跳过..."
          else
            echo "创建新 Release..."
            gh release create "$RELEASE_TAG" \
              --title "$RELEASE_TITLE" \
              --notes "$RELEASE_NOTES"
          fi