# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Push Tag

on:
  workflow_dispatch:
    inputs:
        tag_name:
          description: "The tag version you want to push"
          required: true
          type: string
          default: "v0.1"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Push
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: |
        set -e
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git tag ${{ github.event.inputs.tag_name }}
        git push origin ${{ github.event.inputs.tag_name }}
