# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Push Tag

on:
  workflow_dispatch:
    inputs:
        tag_name:
          description: "The tag version you want to push"
          required: true
          type: string
          default: "v0.1"

env:
  RELEASE_TAG: ${{ github.event.inputs.tag_name }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        name: ${{ env.RELEASE_TAG }}
        tag_name: ${{ env.RELEASE_TAG }}
        body: "远程执行命令, 多主机并发"
