# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Push Tag

on:
  workflow_dispatch:
    inputs:
        tag:
          description: "The tag version you want to push"
          required: true
          type: string
          default: "v0.1"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Push
      run: |
        set -e
        git tag ${{ github.event.inputs.tag }}
        git tag
        git push --tags
